name: Validate JSON
on:
  push:
    paths:
      - web/atlas.json
  pull_request:
    paths:
      - web/atlas.json
jobs:
  validate:
    name: Validate JSON
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Validate JSON
        run: |
          pip3 install -r tools/ci/requirements.txt
          python3 tools/ci/validate_json.py web/atlas.json tools/atlas.schema.json